### PR TITLE
table of contents option

### PR DESCRIPTION
**Pull request by adradr**
Simple functionality to support table of contents creation as `README.md` in output root.

### CODE REVIEW

**Comment by adradr** [comment]
@clemlak what do you think?

**Comment by 0xJepsen** [comment]
@clemlak Does look good for merge?

**Comment by CJ42** [comment]
Would be quite interested by this feature too @clemlak

**Comment by adradr** [comment]
I wanted to close this as still had no replies. If anyone wants to use the table of contents I made a package of my forked version and can be installed by `npm i @adradr/hardhat-dodoc`

**Pull request closed without merging**
